# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/sam_tool.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61pi/sam_tool.proto\x12\x07SamTool\"8\n\x08\x66\x65\x61tures\x12\r\n\x05image\x18\x01 \x03(\t\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\"\x18\n\x07results\x12\r\n\x05\x62oxes\x18\x01 \x03(\t28\n\x07SamTool\x12-\n\x04main\x12\x11.SamTool.features\x1a\x10.SamTool.results\"\x00\x62\x06proto3')



_FEATURES = DESCRIPTOR.message_types_by_name['features']
_RESULTS = DESCRIPTOR.message_types_by_name['results']
features = _reflection.GeneratedProtocolMessageType('features', (_message.Message,), {
  'DESCRIPTOR' : _FEATURES,
  '__module__' : 'api.sam_tool_pb2'
  # @@protoc_insertion_point(class_scope:SamTool.features)
  })
_sym_db.RegisterMessage(features)

results = _reflection.GeneratedProtocolMessageType('results', (_message.Message,), {
  'DESCRIPTOR' : _RESULTS,
  '__module__' : 'api.sam_tool_pb2'
  # @@protoc_insertion_point(class_scope:SamTool.results)
  })
_sym_db.RegisterMessage(results)

_SAMTOOL = DESCRIPTOR.services_by_name['SamTool']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FEATURES._serialized_start=31
  _FEATURES._serialized_end=87
  _RESULTS._serialized_start=89
  _RESULTS._serialized_end=113
  _SAMTOOL._serialized_start=115
  _SAMTOOL._serialized_end=171
# @@protoc_insertion_point(module_scope)
